version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: podcast_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine

  backend:
    build:
      context: ..
      dockerfile: infra/Dockerfile.backend
    environment:
      DATABASE_URL: postgresql://user:password@db/podcast_db
      REDIS_URL: redis://redis:6379/0
    depends_on:
      - db
      - redis
    ports:
      - "8000:8000"

  frontend:
    build:
      context: ..
      dockerfile: infra/Dockerfile.frontend
    ports:
      - "3000:3000"

  worker:
    build:
      context: ..
      dockerfile: infra/Dockerfile.backend
    command: celery -A workers.audio_worker worker --loglevel=info
    environment:
      DATABASE_URL: postgresql://user:password@db/podcast_db
      REDIS_URL: redis://redis:6379/0
    depends_on:
      - redis

volumes:
  postgres_data:
